import argparse
from pathlib import Path

import json
import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib import rcParams


def main(input_file: Path, output_file: Path) -> None:
    with input_file.open('r') as fp:
        data = json.load(fp)

    plt.figure(figsize=(20, 12))
    rcParams['font.family'] = 'serif'
    rcParams['font.serif'] = 'Times New Roman'
    plt.tick_params(left=False, bottom=False)
    sns.heatmap(data['z'][::-1], xticklabels=data['x'], yticklabels=data['y'][::-1], cmap="YlGnBu_r")
    plt.savefig(output_file, bbox_inches='tight', dpi=150)


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('input', type=Path, help='Input JSON file, generated by process.py')
    parser.add_argument('output', type=Path, help='Output file containing the figure')
    args = parser.parse_args()
    main(args.input, args.output)
